name: Clean up stale happy stacks every year

on:
  schedule:
    # Runs "At 00:00 on day-of-month 1 in November." (see https://crontab.guru)
    - cron: "0 0 1 11 *"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Clean happy stacks
    runs-on: ubuntu-22.04
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1800
          role-session-name: HappyCleanupSingleCellDPRdevStacks
      - name: Clean up stale happy stacks
        uses: chanzuckerberg/github-actions/.github/actions/happy-cleanup@happy-cleanup-v1.5.0
        with:
          tfe_token: ${{secrets.TFE_TOKEN}}
          # the default stale period to delete a stack is 2 weeks
          # override like this:
          #time: 3 weeks
          #time: 2 days
